// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using grzyby.Data;

#nullable disable

namespace grzyby.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("grzyby.Models.Grzyb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Jadalny")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazwa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rodzina")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZdjecieUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Grzyby");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Jadalny = true,
                            Nazwa = "Borowik szlachetny (Prawdziwek)",
                            Opis = "Duży, mięsisty grzyb o przyjemnym zapachu. Jeden z najbardziej cenionych jadalnych borowików.",
                            Rodzina = "Borowikowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Boletus_edulis.jpg?width=800"
                        },
                        new
                        {
                            Id = 2,
                            Jadalny = false,
                            Nazwa = "Muchomor czerwony",
                            Opis = "Charakterystyczny, trujący grzyb z czerwonym kapeluszem i białymi plamkami.",
                            Rodzina = "Muchomorowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Amanita_muscaria.jpg?width=800"
                        },
                        new
                        {
                            Id = 3,
                            Jadalny = true,
                            Nazwa = "Czubajka kania",
                            Opis = "Duży, parasolowaty grzyb o smacznym miąższu. Bardzo popularny, często smażony na wzór kotletów.",
                            Rodzina = "Pieczarkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Macrolepiota-procera.jpg?width=800"
                        },
                        new
                        {
                            Id = 4,
                            Jadalny = true,
                            Nazwa = "Pieprznik jadalny (Kurka)",
                            Opis = "Żółty, falisty grzyb o owocowym zapachu. Rzadko robaczywieje, wyśmienity w śmietanie.",
                            Rodzina = "Pieprznikowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Cantharellus_cibarius.JPG?width=800"
                        },
                        new
                        {
                            Id = 5,
                            Jadalny = false,
                            Nazwa = "Gąska zielonka",
                            Opis = "Dawniej uważana za jadalną, dziś niezalecana ze względu na możliwe ciężkie zatrucia na długą metę.",
                            Rodzina = "Gąskowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Tricholoma_equestre.jpg?width=800"
                        },
                        new
                        {
                            Id = 6,
                            Jadalny = true,
                            Nazwa = "Podgrzybek brunatny",
                            Opis = "Jeden z najczęściej zbieranych grzybów w Polsce. Miąższ po uciśnięciu lub przekrojeniu lekko sinieje.",
                            Rodzina = "Borowikowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Imleria_badia.jpg?width=800"
                        },
                        new
                        {
                            Id = 7,
                            Jadalny = false,
                            Nazwa = "Muchomor sromotnikowy",
                            Opis = "Śmiertelnie trujący! Często mylony z gąską zielonką lub młodą kanią. Uszkadza wątrobę.",
                            Rodzina = "Muchomorowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Amanita_phalloides.jpg?width=800"
                        },
                        new
                        {
                            Id = 8,
                            Jadalny = true,
                            Nazwa = "Mleczaj rydz",
                            Opis = "Po uszkodzeniu wydziela pomarańczowe mleczko. Uważany za jednego z najsmaczniejszych grzybów.",
                            Rodzina = "Gołąbkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Lactarius_Deliciosus.jpg?width=800"
                        },
                        new
                        {
                            Id = 9,
                            Jadalny = true,
                            Nazwa = "Maślak zwyczajny",
                            Opis = "Jego kapelusz pokryty jest śluzowatą, lepką skórką. Rośnie przeważnie pod sosnami.",
                            Rodzina = "Maślakowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Suillus_luteus.jpg?width=800"
                        },
                        new
                        {
                            Id = 10,
                            Jadalny = false,
                            Nazwa = "Goryczak żółciowy (Szatan)",
                            Opis = "Niejadalny z powodu skrajnie gorzkiego smaku. Podobny do prawdziwka, ale ma różowe rurki.",
                            Rodzina = "Borowikowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Tylopilus_felleus.jpg?width=800"
                        },
                        new
                        {
                            Id = 11,
                            Jadalny = true,
                            Nazwa = "Koźlarz babka",
                            Opis = "Grzyb o łagodnym smaku z charakterystycznym trzonem pokrytym drobnymi, czarniawymi łuskami.",
                            Rodzina = "Borowikowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Leccinum_scabrum.jpg?width=800"
                        },
                        new
                        {
                            Id = 12,
                            Jadalny = true,
                            Nazwa = "Opieńka miodowa",
                            Opis = "Pasożyt drzew. Znakomity grzyb jadalny po dłuższej obróbce termicznej.",
                            Rodzina = "Obrzękowcowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Armillaria_mellea.jpg?width=800"
                        },
                        new
                        {
                            Id = 13,
                            Jadalny = false,
                            Nazwa = "Zasłonak rudy",
                            Opis = "Śmiertelnie trujący grzyb z objawami zatrucia pojawiającymi się po ponad tygodniu.",
                            Rodzina = "Zasłonakowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Cortinarius_rubellus.jpg?width=800"
                        },
                        new
                        {
                            Id = 14,
                            Jadalny = true,
                            Nazwa = "Smardz jadalny",
                            Opis = "Wiosenny grzyb o nietypowej, pofałdowanej główce przypominającej plaster miodu. Pod ochroną.",
                            Rodzina = "Smardzowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Morchella_esculenta.jpg?width=800"
                        },
                        new
                        {
                            Id = 15,
                            Jadalny = true,
                            Nazwa = "Purchawka chropowata",
                            Opis = "Młode owocniki (gdy ich wnętrze jest całkowicie białe) są jadalne i bardzo smaczne.",
                            Rodzina = "Pieczarkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Lycoperdon_perlatum.jpg?width=800"
                        },
                        new
                        {
                            Id = 16,
                            Jadalny = true,
                            Nazwa = "Krasnoborowik ceglastopory",
                            Opis = "Ciemnobrązowy kapelusz i czerwone pory. Mocno sinieje po przekrojeniu. Jadalny po ugotowaniu.",
                            Rodzina = "Borowikowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Neoboletus_luridiformis.jpg?width=800"
                        },
                        new
                        {
                            Id = 17,
                            Jadalny = true,
                            Nazwa = "Podgrzybek zajączek",
                            Opis = "Popularny grzyb o żółtawym trzonie i zamszowym kapeluszu. Rzadko robaczywieje.",
                            Rodzina = "Borowikowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Xerocomus_subtomentosus.jpg?width=800"
                        },
                        new
                        {
                            Id = 18,
                            Jadalny = true,
                            Nazwa = "Siedzuń sosnowy (Szmaciak)",
                            Opis = "Nietypowy, kalafiorowaty grzyb rosnący przy sosnach. Jadalny, wybitny w smaku.",
                            Rodzina = "Siedzuniowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Sparassis_crispa.jpg?width=800"
                        },
                        new
                        {
                            Id = 19,
                            Jadalny = true,
                            Nazwa = "Pieczarka polna",
                            Opis = "Dziko rosnąca krewniaczka pieczarki ze sklepu. Występuje na łąkach i pastwiskach.",
                            Rodzina = "Pieczarkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Agaricus_campestris.jpg?width=800"
                        },
                        new
                        {
                            Id = 20,
                            Jadalny = false,
                            Nazwa = "Muchomor plamisty",
                            Opis = "Silnie trujący! Ma gładki, prążkowany brzeg kapelusza i bulwę z wałeczkowatą pochwą.",
                            Rodzina = "Muchomorowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Amanita_pantherina.jpg?width=800"
                        },
                        new
                        {
                            Id = 21,
                            Jadalny = false,
                            Nazwa = "Muchomor jadowity",
                            Opis = "Śmiertelnie trujący, całkowicie biały grzyb. Bardzo niebezpieczny, mylony z pieczarką.",
                            Rodzina = "Muchomorowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Amanita_virosa.jpg?width=800"
                        },
                        new
                        {
                            Id = 22,
                            Jadalny = false,
                            Nazwa = "Borowik szatański",
                            Opis = "Bardzo rzadki, silnie trujący grzyb o bladoszarym kapeluszu i krwistoczerwonym trzonie.",
                            Rodzina = "Borowikowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Rubroboletus_satanas.jpg?width=800"
                        },
                        new
                        {
                            Id = 23,
                            Jadalny = true,
                            Nazwa = "Gołąbek zielonawy",
                            Opis = "Posiada charakterystyczny, popękany, grynszpanowozielony kapelusz. Bardzo smaczny.",
                            Rodzina = "Gołąbkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Russula_virescens.jpg?width=800"
                        },
                        new
                        {
                            Id = 24,
                            Jadalny = false,
                            Nazwa = "Gołąbek wymiotny",
                            Opis = "Ma piękny, jaskrawoczerwony kapelusz, ale jest silnie piekący i trujący (zaburzenia żołądkowe).",
                            Rodzina = "Gołąbkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Russula_emetica.jpg?width=800"
                        },
                        new
                        {
                            Id = 25,
                            Jadalny = true,
                            Nazwa = "Płomiennica zimowa",
                            Opis = "Cenny grzyb rosnący zimą pod śniegiem na pniach drzew liściastych.",
                            Rodzina = "Kępkowcowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Flammulina_velutipes.jpg?width=800"
                        },
                        new
                        {
                            Id = 26,
                            Jadalny = true,
                            Nazwa = "Boczniak ostrygowaty",
                            Opis = "Popularny grzyb jadalny rosnący na martwym drewnie w kępach. Często uprawiany.",
                            Rodzina = "Boczniakowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Pleurotus_ostreatus.jpg?width=800"
                        },
                        new
                        {
                            Id = 27,
                            Jadalny = true,
                            Nazwa = "Piaskowiec modrzak",
                            Opis = "Jego jasny miąższ po przekrojeniu błyskawicznie zmienia kolor na atramentowoniebieski.",
                            Rodzina = "Piaskowcowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Gyroporus_cyanescens.jpg?width=800"
                        },
                        new
                        {
                            Id = 28,
                            Jadalny = true,
                            Nazwa = "Czernidłak kołpakowaty",
                            Opis = "Jadalny TYLKO młody, gdy blaszki są białe. Z czasem rozpływa się w czarną maź.",
                            Rodzina = "Pieczarkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Coprinus_comatus.jpg?width=800"
                        },
                        new
                        {
                            Id = 29,
                            Jadalny = true,
                            Nazwa = "Sarniak dachówkowaty",
                            Opis = "Przypomina wyglądem sowę. Zamiast rurek posiada pod kapeluszem gęste kolce.",
                            Rodzina = "Kolczakowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Sarcodon_imbricatus.jpg?width=800"
                        },
                        new
                        {
                            Id = 30,
                            Jadalny = true,
                            Nazwa = "Lejkowiec dęty",
                            Opis = "Wygląda jak zwinięty, czarny liść. Po wysuszeniu wybitny grzyb przyprawowy.",
                            Rodzina = "Pieprznikowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Craterellus_cornucopioides.jpg?width=800"
                        },
                        new
                        {
                            Id = 31,
                            Jadalny = true,
                            Nazwa = "Kolczak obłączasty",
                            Opis = "Rośnie w mchu, pod kapeluszem posiada gęste, białawe kolce zamiast blaszek.",
                            Rodzina = "Kolczakowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Hydnum_repandum.jpg?width=800"
                        },
                        new
                        {
                            Id = 32,
                            Jadalny = false,
                            Nazwa = "Maślanka wiązkowa",
                            Opis = "Pospolity, zółto-zielony grzyb rosnący gęstymi kępami na pniach. Gorzki i trujący.",
                            Rodzina = "Pierścieniakowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Hypholoma_fasciculare.jpg?width=800"
                        },
                        new
                        {
                            Id = 33,
                            Jadalny = false,
                            Nazwa = "Piestrzenica kasztanowata",
                            Opis = "Przypomina fałdy mózgu. Posiada toksyczną gyromitrynę, jest silnie trująca przed obróbką.",
                            Rodzina = "Krążkownicowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Gyromitra_esculenta.jpg?width=800"
                        },
                        new
                        {
                            Id = 34,
                            Jadalny = false,
                            Nazwa = "Krowiak podwinięty (Olszówka)",
                            Opis = "Udowodniono, że po latach może wywoływać śmiertelną anemię. Zbieranie odradzane.",
                            Rodzina = "Krowiakowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Paxillus_involutus.jpg?width=800"
                        },
                        new
                        {
                            Id = 35,
                            Jadalny = false,
                            Nazwa = "Mleczaj wełnianka",
                            Opis = "Różowawy grzyb z 'wełnistym' brzegiem. Wydziela piekące mleczko, silnie trujący surowy.",
                            Rodzina = "Gołąbkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Lactarius_torminosus.jpg?width=800"
                        },
                        new
                        {
                            Id = 36,
                            Jadalny = true,
                            Nazwa = "Maślak sitarz",
                            Opis = "Kapelusz blado-żółtobrązowy, rurki szerokie, przypominające gąbkę lub sito. Jadalny, choć dość miękki.",
                            Rodzina = "Maślakowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Suillus_bovinus.jpg?width=800"
                        },
                        new
                        {
                            Id = 37,
                            Jadalny = true,
                            Nazwa = "Maślak ziarnisty",
                            Opis = "W odróżnieniu od maślaka zwyczajnego nie ma pierścienia na trzonie. Pyszny grzyb jadalny, rośnie pod sosnami.",
                            Rodzina = "Maślakowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Suillus_granulatus.jpg?width=800"
                        },
                        new
                        {
                            Id = 38,
                            Jadalny = true,
                            Nazwa = "Maślak pstry",
                            Opis = "Kapelusz zamszowy, ciemnożółty lub rdzawy. Miąższ twardszy niż u innych maślaków, lekko sinieje po przekrojeniu.",
                            Rodzina = "Maślakowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Suillus_variegatus.jpg?width=800"
                        },
                        new
                        {
                            Id = 39,
                            Jadalny = true,
                            Nazwa = "Podgrzybek złotawy",
                            Opis = "Powierzchnia kapelusza często popękana, ukazująca czerwonawy miąższ pod spodem. Przeciętny w smaku.",
                            Rodzina = "Borowikowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Xerocomellus_chrysenteron.jpg?width=800"
                        },
                        new
                        {
                            Id = 40,
                            Jadalny = true,
                            Nazwa = "Borowik ponury",
                            Opis = "Posiada czerwonawą siateczkę na trzonie i ciemne pory. Surowy jest trujący, jadalny dopiero po długim gotowaniu.",
                            Rodzina = "Borowikowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Suillellus_luridus.jpg?width=800"
                        },
                        new
                        {
                            Id = 41,
                            Jadalny = true,
                            Nazwa = "Borowik usiatkowany",
                            Opis = "Kuzyn prawdziwka o jasnobrązowym, zamszowym kapeluszu i wyraźnej siateczce na niemal całym trzonie.",
                            Rodzina = "Borowikowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Boletus_reticulatus.jpg?width=800"
                        },
                        new
                        {
                            Id = 42,
                            Jadalny = true,
                            Nazwa = "Borowik sosnowy",
                            Opis = "Prawdziwek o charakterystycznym, bardzo ciemnym, czerwonobrązowym kapeluszu. Niezwykle ceniony grzybiarsko.",
                            Rodzina = "Borowikowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Boletus_pinophilus.jpg?width=800"
                        },
                        new
                        {
                            Id = 43,
                            Jadalny = true,
                            Nazwa = "Koźlarz czerwony",
                            Opis = "Wybitny grzyb o jaskrawym, ceglastoczerwonym kapeluszu, twardym miąższu i łuskowatym trzonie. Rośnie pod osikami.",
                            Rodzina = "Borowikowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Leccinum_aurantiacum.jpg?width=800"
                        },
                        new
                        {
                            Id = 44,
                            Jadalny = true,
                            Nazwa = "Koźlarz grabowy",
                            Opis = "Często spotykany pod grabami. Po uszkodzeniu jego biały miąższ szybko ciemnieje, stając się fioletowo-czarny.",
                            Rodzina = "Borowikowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Leccinum_pseudoscabrum.jpg?width=800"
                        },
                        new
                        {
                            Id = 45,
                            Jadalny = true,
                            Nazwa = "Koźlarz pomarańczowożółty",
                            Opis = "Grzyb podobny do koźlarza czerwonego, jednak jego łuski na trzonie od początku są czarne. Rośnie z brzozami.",
                            Rodzina = "Borowikowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Leccinum_versipelle.jpg?width=800"
                        },
                        new
                        {
                            Id = 46,
                            Jadalny = false,
                            Nazwa = "Muchomor cytrynowy",
                            Opis = "Kapelusz bladożółty z łatkami. Zapach przypomina surowe ziemniaki. Zwykle uważany za trujący lub niejadalny.",
                            Rodzina = "Muchomorowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Amanita_citrina.jpg?width=800"
                        },
                        new
                        {
                            Id = 47,
                            Jadalny = false,
                            Nazwa = "Muchomor porfirowy",
                            Opis = "O fioletowoszarym odcieniu kapelusza, zapach również ziemniaczany. Zawiera toksyny i jest niejadalny.",
                            Rodzina = "Muchomorowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Amanita_porphyria.jpg?width=800"
                        },
                        new
                        {
                            Id = 48,
                            Jadalny = true,
                            Nazwa = "Muchomor rdzawobrązowy",
                            Opis = "Nie posiada pierścienia na trzonie. Kapelusz gładki, pomarańczowobrązowy. Jadalny po obróbce termicznej.",
                            Rodzina = "Muchomorowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Amanita_fulva.jpg?width=800"
                        },
                        new
                        {
                            Id = 49,
                            Jadalny = true,
                            Nazwa = "Muchomor twardawy",
                            Opis = "Jadalny muchomor (po gotowaniu). Miąższ po przełamaniu powoli przebarwia się na czerwonawy kolor.",
                            Rodzina = "Muchomorowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Amanita_excelsa.jpg?width=800"
                        },
                        new
                        {
                            Id = 50,
                            Jadalny = true,
                            Nazwa = "Pieczarka dwuzarodnikowa",
                            Opis = "To najpopularniejszy grzyb uprawny (pieczarka biała i brązowa w sklepach), jednak występuje również dziko na kompoście.",
                            Rodzina = "Pieczarkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Agaricus_bisporus.jpg?width=800"
                        },
                        new
                        {
                            Id = 51,
                            Jadalny = false,
                            Nazwa = "Pieczarka żółtawa",
                            Opis = "TRUJĄCA! Przy pocieraniu trzonu lub brzegu kapelusza silnie żółknie. Pachnie nieprzyjemnie apteką lub fenolem.",
                            Rodzina = "Pieczarkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Agaricus_xanthodermus.jpg?width=800"
                        },
                        new
                        {
                            Id = 52,
                            Jadalny = true,
                            Nazwa = "Pieczarka leśna",
                            Opis = "Często rośnie w lasach iglastych. Ma kapelusz pokryty brązowymi łuskami. Po przekrojeniu miąższ czerwienieje.",
                            Rodzina = "Pieczarkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Agaricus_silvaticus.jpg?width=800"
                        },
                        new
                        {
                            Id = 53,
                            Jadalny = true,
                            Nazwa = "Gąska niekształtna",
                            Opis = "Szara gąska rosnąca głównie późną jesienią w lasach sosnowych. Bardzo smaczna po ugotowaniu.",
                            Rodzina = "Gąskowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Tricholoma_portentosum.jpg?width=800"
                        },
                        new
                        {
                            Id = 54,
                            Jadalny = false,
                            Nazwa = "Gąska siarkowa",
                            Opis = "Grzyb o jaskrawożółtym kolorze i bardzo silnym, nieprzyjemnym zapachu gazu świetlnego. Niejadalny/trujący.",
                            Rodzina = "Gąskowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Tricholoma_sulphureum.jpg?width=800"
                        },
                        new
                        {
                            Id = 55,
                            Jadalny = true,
                            Nazwa = "Gołąbek jadalny",
                            Opis = "Posiada różowo-cielisty kapelusz, z którego skórka nie zdejmuje się do końca (zostawia obwódkę). Twardy i smaczny.",
                            Rodzina = "Gołąbkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Russula_vesca.jpg?width=800"
                        },
                        new
                        {
                            Id = 56,
                            Jadalny = true,
                            Nazwa = "Gołąbek winny",
                            Opis = "Ciemnoczerwony kapelusz, wydziela zapach przypominający śledzie. Miąższ ciemnieje po uszkodzeniu. Jadalny.",
                            Rodzina = "Gołąbkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Russula_xerampelina.jpg?width=800"
                        },
                        new
                        {
                            Id = 57,
                            Jadalny = false,
                            Nazwa = "Gołąbek brudnożółty",
                            Opis = "Bardzo pospolity w polskich lasach. Ma żółtawy kapelusz i dość ostry smak na surowo. Mało wartościowy kulinarnie.",
                            Rodzina = "Gołąbkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Russula_ochroleuca.jpg?width=800"
                        },
                        new
                        {
                            Id = 58,
                            Jadalny = false,
                            Nazwa = "Mleczaj rudy",
                            Opis = "Ceglastoczerwony kapelusz ze szpicem. Wydziela białe mleczko, które ma ekstremalnie palący, ostry smak. Niejadalny.",
                            Rodzina = "Gołąbkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Lactarius_rufus.jpg?width=800"
                        },
                        new
                        {
                            Id = 59,
                            Jadalny = true,
                            Nazwa = "Mleczaj smaczny",
                            Opis = "Kapelusz pomarańczowobrązowy, obficie wydziela łagodne, białe mleczko pachnące śledziami. Znakomity na surowo po usmażeniu.",
                            Rodzina = "Gołąbkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Lactifluus_volemus.jpg?width=800"
                        },
                        new
                        {
                            Id = 60,
                            Jadalny = true,
                            Nazwa = "Mleczaj kamforowy",
                            Opis = "Mały, bordowy grzyb wydzielający zapach maggi, cykorii lub kamfory. Po wysuszeniu doskonały jako przyprawa.",
                            Rodzina = "Gołąbkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Lactarius_camphoratus.jpg?width=800"
                        },
                        new
                        {
                            Id = 61,
                            Jadalny = true,
                            Nazwa = "Rycerzyk czerwonozłoty",
                            Opis = "Przepiękny grzyb o żółtym miąższu i fioletowoczerwonym kapeluszu rosnący na martwym drewnie. Jadalny, choć smakuje drzewem.",
                            Rodzina = "Gąskowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Tricholomopsis_rutilans.jpg?width=800"
                        },
                        new
                        {
                            Id = 62,
                            Jadalny = true,
                            Nazwa = "Pieniążek dębowy",
                            Opis = "Drobny grzybek o cienkim trzonie z jasnobrązowym kapeluszem. Występuje masowo pod dębami. Uznawany za jadalny po obróbce.",
                            Rodzina = "Omphalotaceae",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Gymnopus_dryophilus.jpg?width=800"
                        },
                        new
                        {
                            Id = 63,
                            Jadalny = false,
                            Nazwa = "Czernidłak pospolity",
                            Opis = "TRUJĄCY w połączeniu z alkoholem (zawiera kopryną blokującą metabolizm alkoholu). Bez alkoholu teoretycznie jadalny (młody).",
                            Rodzina = "Kruchaweczkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Coprinopsis_atramentaria.jpg?width=800"
                        },
                        new
                        {
                            Id = 64,
                            Jadalny = true,
                            Nazwa = "Czernidłak błyszczący",
                            Opis = "Rośnie kępami na pniach, a jego kapelusz pokryty jest błyszczącymi, mikowymi ziarenkami. Jadalne tylko białe formy młode.",
                            Rodzina = "Kruchaweczkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Coprinellus_micaceus.jpg?width=800"
                        },
                        new
                        {
                            Id = 65,
                            Jadalny = false,
                            Nazwa = "Lejkówka jadowita",
                            Opis = "Mały, niepozorny biały grzyb rosnący na trawnikach i pastwiskach. Silnie trujący – zawiera muskarynę, prowokując ślinotok i zlewne poty.",
                            Rodzina = "Gąskowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Clitocybe_dealbata.jpg?width=800"
                        },
                        new
                        {
                            Id = 66,
                            Jadalny = false,
                            Nazwa = "Krowiak aksamitny",
                            Opis = "Posiada masywny, brązowy, grubo zamszowy trzon boczny lub centralny. Rośnie na martwym drewnie. Kwaśny i ciężkostrawny.",
                            Rodzina = "Tapinellaceae",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Tapinella_atrotomentosa.jpg?width=800"
                        },
                        new
                        {
                            Id = 67,
                            Jadalny = false,
                            Nazwa = "Lisówka pomarańczowa",
                            Opis = "Nazywana potocznie 'fałszywą kurką'. Blaszki dużo drobniejsze, cienkie, kapelusz bywa jaskrawszy. Niejadalna, u niektórych wywołuje zatrucia.",
                            Rodzina = "Lisówkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Hygrophoropsis_aurantiaca.jpg?width=800"
                        },
                        new
                        {
                            Id = 68,
                            Jadalny = true,
                            Nazwa = "Twardzioszek przydrożny",
                            Opis = "Rośnie w trawie tworząc słynne 'czarcie kręgi'. Ma mały kapelusz z garbem i bardzo twardy, elastyczny trzon. Ceniony grzyb do zup.",
                            Rodzina = "Twardzioszkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Marasmius_oreades.jpg?width=800"
                        },
                        new
                        {
                            Id = 69,
                            Jadalny = true,
                            Nazwa = "Twardzioszek czosnaczek",
                            Opis = "Drobniutki grzyb na igiełkowatym trzonie o potężnym, intensywnym zapachu czosnku. Wspaniały naturalny aromat do potraw.",
                            Rodzina = "Twardzioszkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Mycetinis_scorodonius.jpg?width=800"
                        },
                        new
                        {
                            Id = 70,
                            Jadalny = true,
                            Nazwa = "Klejówka świerkowa",
                            Opis = "Kapelusz szary i gruby obficie pokryty przezroczystym, grubym śluzem, który należy zerwać. Gotowany zmienia kolor na fioletowy. Smaczna.",
                            Rodzina = "Klejówkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Gomphidius_glutinosus.jpg?width=800"
                        },
                        new
                        {
                            Id = 71,
                            Jadalny = true,
                            Nazwa = "Zasłonak fioletowy",
                            Opis = "Wygląda zjawiskowo: jest od stóp do głów atramentowofioletowy. Jadalny, choć w Polsce rzadki (często pod ochroną).",
                            Rodzina = "Zasłonakowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Cortinarius_violaceus.jpg?width=800"
                        },
                        new
                        {
                            Id = 72,
                            Jadalny = true,
                            Nazwa = "Purchawka gruszkowata",
                            Opis = "Ma gładką skórkę i w przeciwieństwie do chropowatej – rośnie licznie na martwym drewnie, a nie w ziemi. Jadalna dopóki biała w środku.",
                            Rodzina = "Pieczarkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Apioperdon_pyriforme.jpg?width=800"
                        },
                        new
                        {
                            Id = 73,
                            Jadalny = true,
                            Nazwa = "Czasznica olbrzymia",
                            Opis = "Biała, kulista purchawka osiągająca wielkość piłki lekarskiej (nawet kilkanaście kilogramów!). Wybitna na kotlety, gdy wnętrze jest idealnie białe.",
                            Rodzina = "Pieczarkowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Calvatia_gigantea.jpg?width=800"
                        },
                        new
                        {
                            Id = 74,
                            Jadalny = true,
                            Nazwa = "Sromotnik smrodliwy",
                            Opis = "W dorosłej formie wydziela odór psującego się mięsa wabiąc muchy. Młoda forma ('czarcie jajo') jest jadalna i w wielu krajach stanowi rarytas.",
                            Rodzina = "Sromotnikowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Phallus_impudicus.jpg?width=800"
                        },
                        new
                        {
                            Id = 75,
                            Jadalny = true,
                            Nazwa = "Żagiew łuskowa",
                            Opis = "Duża huba o zapachu świeżego ogórka lub arbuza. Pasożyt drzew liściastych. Bardzo młode owocniki są jadalne po ugotowaniu.",
                            Rodzina = "Żagwiowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Cerioporus_squamosus.jpg?width=800"
                        },
                        new
                        {
                            Id = 76,
                            Jadalny = false,
                            Nazwa = "Łuskwiak nastroszony",
                            Opis = "Cały pokryty gęstymi, suchymi, sterczącymi łuskami. Występuje kępami u podnóży drzew. Jest twardy, gorzkawy i może wywołać niestrawność.",
                            Rodzina = "Pierścieniakowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Pholiota_squarrosa.jpg?width=800"
                        },
                        new
                        {
                            Id = 77,
                            Jadalny = true,
                            Nazwa = "Ucho bzowe",
                            Opis = "Często nazywany 'grzybem Mun'. Elastyczny, żelatynowaty grzyb rosnący głównie zimą na gałęziach czarnego bzu. Idealny do dań kuchni azjatyckiej.",
                            Rodzina = "Uszakowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Auricularia_auricula-judae.jpg?width=800"
                        },
                        new
                        {
                            Id = 78,
                            Jadalny = true,
                            Nazwa = "Żółciak siarkowy",
                            Opis = "Wydaje jaskrawożółte półki na drzewach liściastych. Potocznie zwany 'leśnym kurczakiem' bo smażony w panierce mocno go przypomina (jadalny tylko młody).",
                            Rodzina = "Żagwiowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Laetiporus_sulphureus.jpg?width=800"
                        },
                        new
                        {
                            Id = 79,
                            Jadalny = true,
                            Nazwa = "Maślanka łagodna",
                            Opis = "W odróżnieniu od trującej maślanki wiązkowej ma rdzawy, gładki kapelusz i łagodny smak. Dobry grzyb jadalny używany na przetwory.",
                            Rodzina = "Pierścieniakowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Hypholoma_capnoides.jpg?width=800"
                        },
                        new
                        {
                            Id = 80,
                            Jadalny = true,
                            Nazwa = "Opieńka ciemna",
                            Opis = "Równie popularna i smaczna jak miodowa, ale zazwyczaj posiada nieco ciemniejszy, mocniej pokryty łuseczkami kapelusz.",
                            Rodzina = "Obrzękowcowate",
                            ZdjecieUrl = "https://commons.wikimedia.org/wiki/Special:FilePath/Armillaria_ostoyae.jpg?width=800"
                        });
                });

            modelBuilder.Entity("grzyby.Models.Komentarz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDodania")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("WpisId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("WpisId");

                    b.ToTable("Komentarze");
                });

            modelBuilder.Entity("grzyby.Models.TodoItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDone")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TodoItems");
                });

            modelBuilder.Entity("grzyby.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("grzyby.Models.Wpis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataDodania")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tresc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tytul")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Wpisy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("grzyby.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("grzyby.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("grzyby.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("grzyby.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("grzyby.Models.Komentarz", b =>
                {
                    b.HasOne("grzyby.Models.User", "Author")
                        .WithMany("Komentarze")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("grzyby.Models.Wpis", "Wpis")
                        .WithMany("Komentarze")
                        .HasForeignKey("WpisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Wpis");
                });

            modelBuilder.Entity("grzyby.Models.Wpis", b =>
                {
                    b.HasOne("grzyby.Models.User", "Author")
                        .WithMany("Wpisy")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("grzyby.Models.User", b =>
                {
                    b.Navigation("Komentarze");

                    b.Navigation("Wpisy");
                });

            modelBuilder.Entity("grzyby.Models.Wpis", b =>
                {
                    b.Navigation("Komentarze");
                });
#pragma warning restore 612, 618
        }
    }
}
